### ISSUE TITLE
Where I can get .crx to Install this Extension?

### ISSUE THREAD

**Issue by j4anm4** [zhad3/cookies.txt-importer-for-chrome#2] opened 2023-08-22 11:43 UTC
Where I can get .crx to Install this Extension

**Comment by zhad3** [comment] 2023-08-23 06:37
Hi @j4anm4 , there is no .crx file.
To install this extension either clone the repo or download it as a zip file then follow the steps detailed under "Load an unpacked extension" here:  https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked.

Duplicate of #1

**Closed as completed by zhad3** 2023-08-23 06:37 UTC
